- hosts: bahmni-emr
  become: yes
  roles:
    - { role: implementer-interface, tags: implementer_interface }
    - { role: bahmni-apps, tags: bahmni_apps }
    - { role: bahmni-core, tags: bahmni_core }
    - { role: appointments, tags: appointments }
    - { role: bahmni-ie-apps, tags: bahmni_ie_apps }
    - { role: openmrs-ui-framework, tags: openmrs_ui_framework }
    - { role: appointment-frontend, tags: appointment_frontend }
    - { role: visit-close-module, tags: visit_close_module }
    - { role: emr-api-omod, tags: emr_api_omod }
    - { role: event-omod, tags: event_omod }
    - { role: patient-identifier-generator, tags: patient_identifier_generator }
