implementerinterface: https://bahmni-msf.s3.ap-south-1.amazonaws.com/haiti-release-artefacts/release-1.2/bahmni-implementer-interface.noarch.rpm
bahmniapps: https://bahmni-msf.s3.ap-south-1.amazonaws.com/haiti-release-artefacts/release-1.2/bahmniapps.zip
appointments: https://bahmni-msf.s3.ap-south-1.amazonaws.com/haiti-release-artefacts/release-1.0/appointments.omod
bahmnicore: https://bahmni-msf.s3.ap-south-1.amazonaws.com/haiti-release-artefacts/release-1.0/bahmnicore-0.92-SNAPSHOT.omod
bahmniieapps: https://bahmni-msf.s3.ap-south-1.amazonaws.com/haiti-release-artefacts/release-1.2/bahmni.ie.apps.omod
uiframework: https://dl.bintray.com/openmrs/omod/uiframework-3.19.0.omod
